import { Jost } from 'next/font/google'
import './globals.css'
import Header from '@/components/navigationbar/Header'
import Footer from '@/components/footer/Footer'
import { Toaster } from 'sonner'

const jost = Jost({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${jost.className } max-w-[2100px] mx-auto` } >
      <Header />
        {children}
        <Toaster richColors  />

        <Footer /></body>
    </html>
  )
}
